export enum ContentType {
    JSON = 'application/json',
    HTML = 'text/html',
    TEXT = 'text/plain',
    XML = 'application/xml',
    FORM_URLENCODED = 'application/x-www-form-urlencoded',
    MULTIPART_FORM_DATA = 'multipart/form-data',
    JAVASCRIPT = 'application/javascript',
    CSS = 'text/css',
    CSV = 'text/csv',
    IMAGE_PNG = 'image/png',
    IMAGE_JPEG = 'image/jpeg',
    IMAGE_GIF = 'image/gif',
    IMAGE_BMP = 'image/bmp',
    IMAGE_WEBP = 'image/webp',
    AUDIO_MPEG = 'audio/mpeg',
    AUDIO_OGG = 'audio/ogg',
    VIDEO_MP4 = 'video/mp4',
    VIDEO_WEBM = 'video/webm',
    APPLICATION_PDF = 'application/pdf',
    APPLICATION_ZIP = 'application/zip'
}
